//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class TableManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(TableManager), typeof(System.Object));
		L.RegFunction("ReadDataConfig", ReadDataConfig);
		L.RegFunction("LuaReadDataConfig", LuaReadDataConfig);
		L.RegFunction("New", _CreateTableManager);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Instance", get_Instance, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateTableManager(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				TableManager obj = new TableManager();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: TableManager.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ReadDataConfig(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			TableManager obj = (TableManager)ToLua.CheckObject<TableManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			byte[] o = obj.ReadDataConfig(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LuaReadDataConfig(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			TableManager obj = (TableManager)ToLua.CheckObject<TableManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			LuaInterface.LuaByteBuffer o = obj.LuaReadDataConfig(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Instance(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, TableManager.Instance);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

