//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: Active.proto
namespace active
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActiveInfo")]
  public partial class ActiveInfo : global::ProtoBuf.IExtensible
  {
    public ActiveInfo() {}
    
    private int _activeNumber;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"activeNumber", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int activeNumber
    {
      get { return _activeNumber; }
      set { _activeNumber = value; }
    }
    private readonly global::System.Collections.Generic.List<long> _activeProgress = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(2, Name=@"activeProgress", DataFormat = global::ProtoBuf.DataFormat.TwosComplement, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<long> activeProgress
    {
      get { return _activeProgress; }
    }
  
    private int _reward;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"reward", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int reward
    {
      get { return _reward; }
      set { _reward = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetActiveRewardRequest")]
  public partial class GetActiveRewardRequest : global::ProtoBuf.IExtensible
  {
    public GetActiveRewardRequest() {}
    
    private readonly global::System.Collections.Generic.List<int> _id = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<int> id
    {
      get { return _id; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}