//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: Auction.proto
// Note: requires additional types generated from: Bag.proto
namespace auction
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AuctionItemInfo")]
  public partial class AuctionItemInfo : global::ProtoBuf.IExtensible
  {
    public AuctionItemInfo() {}
    
    private long _roleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private bag.BagItemInfo _item;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bag.BagItemInfo item
    {
      get { return _item; }
      set { _item = value; }
    }
    private int _price;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"price", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int price
    {
      get { return _price; }
      set { _price = value; }
    }
    private long _addTime;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"addTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long addTime
    {
      get { return _addTime; }
      set { _addTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AuctionItemList")]
  public partial class AuctionItemList : global::ProtoBuf.IExtensible
  {
    public AuctionItemList() {}
    

    private auction.GetAuctionItemsRequest _request = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"request", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public auction.GetAuctionItemsRequest request
    {
      get { return _request; }
      set { _request = value; }
    }
    private readonly global::System.Collections.Generic.List<auction.AuctionItemInfo> _items = new global::System.Collections.Generic.List<auction.AuctionItemInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<auction.AuctionItemInfo> items
    {
      get { return _items; }
    }
  

    private int? _taxRate;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"taxRate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int taxRate
    {
      get { return _taxRate?? default(int); }
      set { _taxRate = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool taxRateSpecified
    {
      get { return _taxRate != null; }
      set { if (value == (_taxRate== null)) _taxRate = value ? taxRate : (int?)null; }
    }
    private bool ShouldSerializetaxRate() { return taxRateSpecified; }
    private void ResettaxRate() { taxRateSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetAuctionItemsRequest")]
  public partial class GetAuctionItemsRequest : global::ProtoBuf.IExtensible
  {
    public GetAuctionItemsRequest() {}
    
    private int _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _subType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"subType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int subType
    {
      get { return _subType; }
      set { _subType = value; }
    }
    private int _page;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"page", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int page
    {
      get { return _page; }
      set { _page = value; }
    }
    private int _minLevel;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"minLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int minLevel
    {
      get { return _minLevel; }
      set { _minLevel = value; }
    }
    private int _maxLevel;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"maxLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maxLevel
    {
      get { return _maxLevel; }
      set { _maxLevel = value; }
    }
    private int _sex;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private int _career;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"career", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int career
    {
      get { return _career; }
      set { _career = value; }
    }

    private int? _toatlPageCount;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"toatlPageCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int toatlPageCount
    {
      get { return _toatlPageCount?? default(int); }
      set { _toatlPageCount = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool toatlPageCountSpecified
    {
      get { return _toatlPageCount != null; }
      set { if (value == (_toatlPageCount== null)) _toatlPageCount = value ? toatlPageCount : (int?)null; }
    }
    private bool ShouldSerializetoatlPageCount() { return toatlPageCountSpecified; }
    private void ResettoatlPageCount() { toatlPageCountSpecified = false; }
    
    private bool _sortByPrice;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"sortByPrice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool sortByPrice
    {
      get { return _sortByPrice; }
      set { _sortByPrice = value; }
    }
    private bool _sortDesc;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"sortDesc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool sortDesc
    {
      get { return _sortDesc; }
      set { _sortDesc = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddToShelfRequest")]
  public partial class AddToShelfRequest : global::ProtoBuf.IExtensible
  {
    public AddToShelfRequest() {}
    
    private int _bagIndex;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"bagIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bagIndex
    {
      get { return _bagIndex; }
      set { _bagIndex = value; }
    }
    private int _count;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private int _price;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"price", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int price
    {
      get { return _price; }
      set { _price = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddToShelfResponse")]
  public partial class AddToShelfResponse : global::ProtoBuf.IExtensible
  {
    public AddToShelfResponse() {}
    
    private int _bagIndex;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"bagIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bagIndex
    {
      get { return _bagIndex; }
      set { _bagIndex = value; }
    }
    private auction.AuctionItemInfo _item;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public auction.AuctionItemInfo item
    {
      get { return _item; }
      set { _item = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReAddToShelfRequest")]
  public partial class ReAddToShelfRequest : global::ProtoBuf.IExtensible
  {
    public ReAddToShelfRequest() {}
    
    private long _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _price;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"price", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int price
    {
      get { return _price; }
      set { _price = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemIdMsg")]
  public partial class ItemIdMsg : global::ProtoBuf.IExtensible
  {
    public ItemIdMsg() {}
    
    private long _itemId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long itemId
    {
      get { return _itemId; }
      set { _itemId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}