//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: Chat.proto
namespace chat
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatRequest")]
  public partial class ChatRequest : global::ProtoBuf.IExtensible
  {
    public ChatRequest() {}
    
    private int _channel;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"channel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int channel
    {
      get { return _channel; }
      set { _channel = value; }
    }
    private string _message;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }

    private string _sendTo;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sendTo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sendTo
    {
      get { return _sendTo?? ""; }
      set { _sendTo = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool sendToSpecified
    {
      get { return _sendTo != null; }
      set { if (value == (_sendTo== null)) _sendTo = value ? sendTo : (string)null; }
    }
    private bool ShouldSerializesendTo() { return sendToSpecified; }
    private void ResetsendTo() { sendToSpecified = false; }
    

    private int? _type;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type?? default(int); }
      set { _type = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool typeSpecified
    {
      get { return _type != null; }
      set { if (value == (_type== null)) _type = value ? type : (int?)null; }
    }
    private bool ShouldSerializetype() { return typeSpecified; }
    private void Resettype() { typeSpecified = false; }
    

    private string _sendToName;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"sendToName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sendToName
    {
      get { return _sendToName?? ""; }
      set { _sendToName = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool sendToNameSpecified
    {
      get { return _sendToName != null; }
      set { if (value == (_sendToName== null)) _sendToName = value ? sendToName : (string)null; }
    }
    private bool ShouldSerializesendToName() { return sendToNameSpecified; }
    private void ResetsendToName() { sendToNameSpecified = false; }
    

    private int? _quickChatId;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"quickChatId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int quickChatId
    {
      get { return _quickChatId?? default(int); }
      set { _quickChatId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool quickChatIdSpecified
    {
      get { return _quickChatId != null; }
      set { if (value == (_quickChatId== null)) _quickChatId = value ? quickChatId : (int?)null; }
    }
    private bool ShouldSerializequickChatId() { return quickChatIdSpecified; }
    private void ResetquickChatId() { quickChatIdSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatMessage")]
  public partial class ChatMessage : global::ProtoBuf.IExtensible
  {
    public ChatMessage() {}
    
    private long _sender;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long sender
    {
      get { return _sender; }
      set { _sender = value; }
    }

    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name?? ""; }
      set { _name = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool nameSpecified
    {
      get { return _name != null; }
      set { if (value == (_name== null)) _name = value ? name : (string)null; }
    }
    private bool ShouldSerializename() { return nameSpecified; }
    private void Resetname() { nameSpecified = false; }
    
    private int _channel;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"channel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int channel
    {
      get { return _channel; }
      set { _channel = value; }
    }
    private string _message;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }

    private string _sendTo;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"sendTo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sendTo
    {
      get { return _sendTo?? ""; }
      set { _sendTo = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool sendToSpecified
    {
      get { return _sendTo != null; }
      set { if (value == (_sendTo== null)) _sendTo = value ? sendTo : (string)null; }
    }
    private bool ShouldSerializesendTo() { return sendToSpecified; }
    private void ResetsendTo() { sendToSpecified = false; }
    

    private bool? _isVip;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"isVip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isVip
    {
      get { return _isVip?? default(bool); }
      set { _isVip = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool isVipSpecified
    {
      get { return _isVip != null; }
      set { if (value == (_isVip== null)) _isVip = value ? isVip : (bool?)null; }
    }
    private bool ShouldSerializeisVip() { return isVipSpecified; }
    private void ResetisVip() { isVipSpecified = false; }
    

    private int? _type;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type?? default(int); }
      set { _type = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool typeSpecified
    {
      get { return _type != null; }
      set { if (value == (_type== null)) _type = value ? type : (int?)null; }
    }
    private bool ShouldSerializetype() { return typeSpecified; }
    private void Resettype() { typeSpecified = false; }
    

    private int? _quickChatId;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"quickChatId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int quickChatId
    {
      get { return _quickChatId?? default(int); }
      set { _quickChatId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool quickChatIdSpecified
    {
      get { return _quickChatId != null; }
      set { if (value == (_quickChatId== null)) _quickChatId = value ? quickChatId : (int?)null; }
    }
    private bool ShouldSerializequickChatId() { return quickChatIdSpecified; }
    private void ResetquickChatId() { quickChatIdSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}