//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: Fight.proto
namespace fight
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EffectedTarget")]
  public partial class EffectedTarget : global::ProtoBuf.IExtensible
  {
    public EffectedTarget() {}
    
    private long _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long id
    {
      get { return _id; }
      set { _id = value; }
    }

    private int? _deltaHP;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"deltaHP", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int deltaHP
    {
      get { return _deltaHP?? default(int); }
      set { _deltaHP = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool deltaHPSpecified
    {
      get { return _deltaHP != null; }
      set { if (value == (_deltaHP== null)) _deltaHP = value ? deltaHP : (int?)null; }
    }
    private bool ShouldSerializedeltaHP() { return deltaHPSpecified; }
    private void ResetdeltaHP() { deltaHPSpecified = false; }
    

    private int? _hp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hp
    {
      get { return _hp?? default(int); }
      set { _hp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool hpSpecified
    {
      get { return _hp != null; }
      set { if (value == (_hp== null)) _hp = value ? hp : (int?)null; }
    }
    private bool ShouldSerializehp() { return hpSpecified; }
    private void Resethp() { hpSpecified = false; }
    

    private int? _buff;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"buff", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int buff
    {
      get { return _buff?? default(int); }
      set { _buff = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool buffSpecified
    {
      get { return _buff != null; }
      set { if (value == (_buff== null)) _buff = value ? buff : (int?)null; }
    }
    private bool ShouldSerializebuff() { return buffSpecified; }
    private void Resetbuff() { buffSpecified = false; }
    

    private int? _innerPower;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"innerPower", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int innerPower
    {
      get { return _innerPower?? default(int); }
      set { _innerPower = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool innerPowerSpecified
    {
      get { return _innerPower != null; }
      set { if (value == (_innerPower== null)) _innerPower = value ? innerPower : (int?)null; }
    }
    private bool ShouldSerializeinnerPower() { return innerPowerSpecified; }
    private void ResetinnerPower() { innerPowerSpecified = false; }
    

    private int? _newX;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"newX", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int newX
    {
      get { return _newX?? default(int); }
      set { _newX = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool newXSpecified
    {
      get { return _newX != null; }
      set { if (value == (_newX== null)) _newX = value ? newX : (int?)null; }
    }
    private bool ShouldSerializenewX() { return newXSpecified; }
    private void ResetnewX() { newXSpecified = false; }
    

    private int? _newY;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"newY", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int newY
    {
      get { return _newY?? default(int); }
      set { _newY = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool newYSpecified
    {
      get { return _newY != null; }
      set { if (value == (_newY== null)) _newY = value ? newY : (int?)null; }
    }
    private bool ShouldSerializenewY() { return newYSpecified; }
    private void ResetnewY() { newYSpecified = false; }
    

    private bool? _jade;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"jade", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool jade
    {
      get { return _jade?? default(bool); }
      set { _jade = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool jadeSpecified
    {
      get { return _jade != null; }
      set { if (value == (_jade== null)) _jade = value ? jade : (bool?)null; }
    }
    private bool ShouldSerializejade() { return jadeSpecified; }
    private void Resetjade() { jadeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SkillEffect")]
  public partial class SkillEffect : global::ProtoBuf.IExtensible
  {
    public SkillEffect() {}
    
    private long _performer;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"performer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long performer
    {
      get { return _performer; }
      set { _performer = value; }
    }
    private int _skillId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"skillId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skillId
    {
      get { return _skillId; }
      set { _skillId = value; }
    }

    private int? _mp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"mp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mp
    {
      get { return _mp?? default(int); }
      set { _mp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool mpSpecified
    {
      get { return _mp != null; }
      set { if (value == (_mp== null)) _mp = value ? mp : (int?)null; }
    }
    private bool ShouldSerializemp() { return mpSpecified; }
    private void Resetmp() { mpSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<fight.EffectedTarget> _targets = new global::System.Collections.Generic.List<fight.EffectedTarget>();
    [global::ProtoBuf.ProtoMember(4, Name=@"targets", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<fight.EffectedTarget> targets
    {
      get { return _targets; }
    }
  

    private long? _time;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long time
    {
      get { return _time?? default(long); }
      set { _time = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool timeSpecified
    {
      get { return _time != null; }
      set { if (value == (_time== null)) _time = value ? time : (long?)null; }
    }
    private bool ShouldSerializetime() { return timeSpecified; }
    private void Resettime() { timeSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<long> _missedIds = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(6, Name=@"missedIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<long> missedIds
    {
      get { return _missedIds; }
    }
  

    private long? _exp;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long exp
    {
      get { return _exp?? default(long); }
      set { _exp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool expSpecified
    {
      get { return _exp != null; }
      set { if (value == (_exp== null)) _exp = value ? exp : (long?)null; }
    }
    private bool ShouldSerializeexp() { return expSpecified; }
    private void Resetexp() { expSpecified = false; }
    

    private int? _newX;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"newX", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int newX
    {
      get { return _newX?? default(int); }
      set { _newX = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool newXSpecified
    {
      get { return _newX != null; }
      set { if (value == (_newX== null)) _newX = value ? newX : (int?)null; }
    }
    private bool ShouldSerializenewX() { return newXSpecified; }
    private void ResetnewX() { newXSpecified = false; }
    

    private int? _newY;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"newY", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int newY
    {
      get { return _newY?? default(int); }
      set { _newY = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool newYSpecified
    {
      get { return _newY != null; }
      set { if (value == (_newY== null)) _newY = value ? newY : (int?)null; }
    }
    private bool ShouldSerializenewY() { return newYSpecified; }
    private void ResetnewY() { newYSpecified = false; }
    

    private long? _mainTargetId;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"mainTargetId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long mainTargetId
    {
      get { return _mainTargetId?? default(long); }
      set { _mainTargetId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool mainTargetIdSpecified
    {
      get { return _mainTargetId != null; }
      set { if (value == (_mainTargetId== null)) _mainTargetId = value ? mainTargetId : (long?)null; }
    }
    private bool ShouldSerializemainTargetId() { return mainTargetIdSpecified; }
    private void ResetmainTargetId() { mainTargetIdSpecified = false; }
    

    private int? _x;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int x
    {
      get { return _x?? default(int); }
      set { _x = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool xSpecified
    {
      get { return _x != null; }
      set { if (value == (_x== null)) _x = value ? x : (int?)null; }
    }
    private bool ShouldSerializex() { return xSpecified; }
    private void Resetx() { xSpecified = false; }
    

    private int? _y;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int y
    {
      get { return _y?? default(int); }
      set { _y = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ySpecified
    {
      get { return _y != null; }
      set { if (value == (_y== null)) _y = value ? y : (int?)null; }
    }
    private bool ShouldSerializey() { return ySpecified; }
    private void Resety() { ySpecified = false; }
    
    private readonly global::System.Collections.Generic.List<long> _isCriticalIds = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(13, Name=@"isCriticalIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<long> isCriticalIds
    {
      get { return _isCriticalIds; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UseSkillRequest")]
  public partial class UseSkillRequest : global::ProtoBuf.IExtensible
  {
    public UseSkillRequest() {}
    
    private int _skillId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"skillId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skillId
    {
      get { return _skillId; }
      set { _skillId = value; }
    }

    private int? _x;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int x
    {
      get { return _x?? default(int); }
      set { _x = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool xSpecified
    {
      get { return _x != null; }
      set { if (value == (_x== null)) _x = value ? x : (int?)null; }
    }
    private bool ShouldSerializex() { return xSpecified; }
    private void Resetx() { xSpecified = false; }
    

    private int? _y;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int y
    {
      get { return _y?? default(int); }
      set { _y = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ySpecified
    {
      get { return _y != null; }
      set { if (value == (_y== null)) _y = value ? y : (int?)null; }
    }
    private bool ShouldSerializey() { return ySpecified; }
    private void Resety() { ySpecified = false; }
    

    private long? _targetId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"targetId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long targetId
    {
      get { return _targetId?? default(long); }
      set { _targetId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool targetIdSpecified
    {
      get { return _targetId != null; }
      set { if (value == (_targetId== null)) _targetId = value ? targetId : (long?)null; }
    }
    private bool ShouldSerializetargetId() { return targetIdSpecified; }
    private void ResettargetId() { targetIdSpecified = false; }
    

    private long? _time;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long time
    {
      get { return _time?? default(long); }
      set { _time = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool timeSpecified
    {
      get { return _time != null; }
      set { if (value == (_time== null)) _time = value ? time : (long?)null; }
    }
    private bool ShouldSerializetime() { return timeSpecified; }
    private void Resettime() { timeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SkillInfo")]
  public partial class SkillInfo : global::ProtoBuf.IExtensible
  {
    public SkillInfo() {}
    
    private int _sid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sid
    {
      get { return _sid; }
      set { _sid = value; }
    }
    private int _level;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }

    private string _name;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name?? ""; }
      set { _name = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool nameSpecified
    {
      get { return _name != null; }
      set { if (value == (_name== null)) _name = value ? name : (string)null; }
    }
    private bool ShouldSerializename() { return nameSpecified; }
    private void Resetname() { nameSpecified = false; }
    
    private long _exp;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long exp
    {
      get { return _exp; }
      set { _exp = value; }
    }

    private long? _lastUseTime;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"lastUseTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long lastUseTime
    {
      get { return _lastUseTime?? default(long); }
      set { _lastUseTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool lastUseTimeSpecified
    {
      get { return _lastUseTime != null; }
      set { if (value == (_lastUseTime== null)) _lastUseTime = value ? lastUseTime : (long?)null; }
    }
    private bool ShouldSerializelastUseTime() { return lastUseTimeSpecified; }
    private void ResetlastUseTime() { lastUseTimeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BufferInfo")]
  public partial class BufferInfo : global::ProtoBuf.IExtensible
  {
    public BufferInfo() {}
    
    private int _bufferId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"bufferId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bufferId
    {
      get { return _bufferId; }
      set { _bufferId = value; }
    }

    private long? _addTime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"addTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long addTime
    {
      get { return _addTime?? default(long); }
      set { _addTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool addTimeSpecified
    {
      get { return _addTime != null; }
      set { if (value == (_addTime== null)) _addTime = value ? addTime : (long?)null; }
    }
    private bool ShouldSerializeaddTime() { return addTimeSpecified; }
    private void ResetaddTime() { addTimeSpecified = false; }
    

    private long? _totalTime;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"totalTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long totalTime
    {
      get { return _totalTime?? default(long); }
      set { _totalTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool totalTimeSpecified
    {
      get { return _totalTime != null; }
      set { if (value == (_totalTime== null)) _totalTime = value ? totalTime : (long?)null; }
    }
    private bool ShouldSerializetotalTime() { return totalTimeSpecified; }
    private void ResettotalTime() { totalTimeSpecified = false; }
    

    private int? _bufferValue;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"bufferValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bufferValue
    {
      get { return _bufferValue?? default(int); }
      set { _bufferValue = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool bufferValueSpecified
    {
      get { return _bufferValue != null; }
      set { if (value == (_bufferValue== null)) _bufferValue = value ? bufferValue : (int?)null; }
    }
    private bool ShouldSerializebufferValue() { return bufferValueSpecified; }
    private void ResetbufferValue() { bufferValueSpecified = false; }
    

    private int? _maxValue;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"maxValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maxValue
    {
      get { return _maxValue?? default(int); }
      set { _maxValue = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool maxValueSpecified
    {
      get { return _maxValue != null; }
      set { if (value == (_maxValue== null)) _maxValue = value ? maxValue : (int?)null; }
    }
    private bool ShouldSerializemaxValue() { return maxValueSpecified; }
    private void ResetmaxValue() { maxValueSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BufferChanged")]
  public partial class BufferChanged : global::ProtoBuf.IExtensible
  {
    public BufferChanged() {}
    
    private long _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long id
    {
      get { return _id; }
      set { _id = value; }
    }

    private fight.BufferInfo _buffer = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"buffer", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public fight.BufferInfo buffer
    {
      get { return _buffer; }
      set { _buffer = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BufferDeltaHP")]
  public partial class BufferDeltaHP : global::ProtoBuf.IExtensible
  {
    public BufferDeltaHP() {}
    
    private long _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _deltaHP;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"deltaHP", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int deltaHP
    {
      get { return _deltaHP; }
      set { _deltaHP = value; }
    }

    private int? _hp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hp
    {
      get { return _hp?? default(int); }
      set { _hp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool hpSpecified
    {
      get { return _hp != null; }
      set { if (value == (_hp== null)) _hp = value ? hp : (int?)null; }
    }
    private bool ShouldSerializehp() { return hpSpecified; }
    private void Resethp() { hpSpecified = false; }
    

    private long? _adder;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"adder", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long adder
    {
      get { return _adder?? default(long); }
      set { _adder = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool adderSpecified
    {
      get { return _adder != null; }
      set { if (value == (_adder== null)) _adder = value ? adder : (long?)null; }
    }
    private bool ShouldSerializeadder() { return adderSpecified; }
    private void Resetadder() { adderSpecified = false; }
    

    private bool? _jade;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"jade", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool jade
    {
      get { return _jade?? default(bool); }
      set { _jade = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool jadeSpecified
    {
      get { return _jade != null; }
      set { if (value == (_jade== null)) _jade = value ? jade : (bool?)null; }
    }
    private bool ShouldSerializejade() { return jadeSpecified; }
    private void Resetjade() { jadeSpecified = false; }
    

    private int? _bufferId;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"bufferId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bufferId
    {
      get { return _bufferId?? default(int); }
      set { _bufferId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool bufferIdSpecified
    {
      get { return _bufferId != null; }
      set { if (value == (_bufferId== null)) _bufferId = value ? bufferId : (int?)null; }
    }
    private bool ShouldSerializebufferId() { return bufferIdSpecified; }
    private void ResetbufferId() { bufferIdSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SkillIdInfo")]
  public partial class SkillIdInfo : global::ProtoBuf.IExtensible
  {
    public SkillIdInfo() {}
    
    private int _skillId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"skillId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skillId
    {
      get { return _skillId; }
      set { _skillId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SkillUpgradeResponse")]
  public partial class SkillUpgradeResponse : global::ProtoBuf.IExtensible
  {
    public SkillUpgradeResponse() {}
    
    private int _oldSkillId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"oldSkillId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int oldSkillId
    {
      get { return _oldSkillId; }
      set { _oldSkillId = value; }
    }
    private fight.SkillInfo _newSkill;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"newSkill", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public fight.SkillInfo newSkill
    {
      get { return _newSkill; }
      set { _newSkill = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UseSkillBookRequest")]
  public partial class UseSkillBookRequest : global::ProtoBuf.IExtensible
  {
    public UseSkillBookRequest() {}
    
    private int _bookConfigId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"bookConfigId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bookConfigId
    {
      get { return _bookConfigId; }
      set { _bookConfigId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SaveSkillShortCutRequest")]
  public partial class SaveSkillShortCutRequest : global::ProtoBuf.IExtensible
  {
    public SaveSkillShortCutRequest() {}
    
    private readonly global::System.Collections.Generic.List<long> _skillShortCut = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(1, Name=@"skillShortCut", DataFormat = global::ProtoBuf.DataFormat.TwosComplement, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<long> skillShortCut
    {
      get { return _skillShortCut; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SaveSkillPositionRequest")]
  public partial class SaveSkillPositionRequest : global::ProtoBuf.IExtensible
  {
    public SaveSkillPositionRequest() {}
    
    private int _skillPosition;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"skillPosition", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skillPosition
    {
      get { return _skillPosition; }
      set { _skillPosition = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SetPkModeRequest")]
  public partial class SetPkModeRequest : global::ProtoBuf.IExtensible
  {
    public SetPkModeRequest() {}
    
    private int _pkMode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"pkMode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pkMode
    {
      get { return _pkMode; }
      set { _pkMode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RemoveSkillMsg")]
  public partial class RemoveSkillMsg : global::ProtoBuf.IExtensible
  {
    public RemoveSkillMsg() {}
    
    private int _sid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sid
    {
      get { return _sid; }
      set { _sid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipSkillCoolDown")]
  public partial class EquipSkillCoolDown : global::ProtoBuf.IExtensible
  {
    public EquipSkillCoolDown() {}
    
    private int _skillGroupId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"skillGroupId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skillGroupId
    {
      get { return _skillGroupId; }
      set { _skillGroupId = value; }
    }
    private long _lastUseTime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"lastUseTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long lastUseTime
    {
      get { return _lastUseTime; }
      set { _lastUseTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}