//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: Gem.proto
// Note: requires additional types generated from: Bag.proto
namespace gem
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GemInfo")]
  public partial class GemInfo : global::ProtoBuf.IExtensible
  {
    public GemInfo() {}
    
    private readonly global::System.Collections.Generic.List<int> _position = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> position
    {
      get { return _position; }
    }
  
    private readonly global::System.Collections.Generic.List<gem.everyGemInfo> _gems = new global::System.Collections.Generic.List<gem.everyGemInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"gems", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<gem.everyGemInfo> gems
    {
      get { return _gems; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"everyGemInfo")]
  public partial class everyGemInfo : global::ProtoBuf.IExtensible
  {
    public everyGemInfo() {}
    
    private int _position;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int position
    {
      get { return _position; }
      set { _position = value; }
    }
    private bag.BagItemInfo _gem;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"gem", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bag.BagItemInfo gem
    {
      get { return _gem; }
      set { _gem = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}