//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: Heart.proto
namespace heart
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Heartbeat")]
  public partial class Heartbeat : global::ProtoBuf.IExtensible
  {
    public Heartbeat() {}
    

    private long? _nowTime;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"nowTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long nowTime
    {
      get { return _nowTime?? default(long); }
      set { _nowTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool nowTimeSpecified
    {
      get { return _nowTime != null; }
      set { if (value == (_nowTime== null)) _nowTime = value ? nowTime : (long?)null; }
    }
    private bool ShouldSerializenowTime() { return nowTimeSpecified; }
    private void ResetnowTime() { nowTimeSpecified = false; }
    

    private long? _clientTime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"clientTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long clientTime
    {
      get { return _clientTime?? default(long); }
      set { _clientTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool clientTimeSpecified
    {
      get { return _clientTime != null; }
      set { if (value == (_clientTime== null)) _clientTime = value ? clientTime : (long?)null; }
    }
    private bool ShouldSerializeclientTime() { return clientTimeSpecified; }
    private void ResetclientTime() { clientTimeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}