//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: Hero.proto
namespace hero
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HeroInfo")]
  public partial class HeroInfo : global::ProtoBuf.IExtensible
  {
    public HeroInfo() {}
    
    private int _heroId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"heroId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int heroId
    {
      get { return _heroId; }
      set { _heroId = value; }
    }
    private int _level;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _dayFightNum;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"dayFightNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dayFightNum
    {
      get { return _dayFightNum; }
      set { _dayFightNum = value; }
    }
    private long _summonTime;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"summonTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long summonTime
    {
      get { return _summonTime; }
      set { _summonTime = value; }
    }

    private long? _activeTime;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"activeTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long activeTime
    {
      get { return _activeTime?? default(long); }
      set { _activeTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool activeTimeSpecified
    {
      get { return _activeTime != null; }
      set { if (value == (_activeTime== null)) _activeTime = value ? activeTime : (long?)null; }
    }
    private bool ShouldSerializeactiveTime() { return activeTimeSpecified; }
    private void ResetactiveTime() { activeTimeSpecified = false; }
    

    private int? _totalLoginDays;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"totalLoginDays", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int totalLoginDays
    {
      get { return _totalLoginDays?? default(int); }
      set { _totalLoginDays = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool totalLoginDaysSpecified
    {
      get { return _totalLoginDays != null; }
      set { if (value == (_totalLoginDays== null)) _totalLoginDays = value ? totalLoginDays : (int?)null; }
    }
    private bool ShouldSerializetotalLoginDays() { return totalLoginDaysSpecified; }
    private void ResettotalLoginDays() { totalLoginDaysSpecified = false; }
    

    private bool? _receiveYuanBao;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"receiveYuanBao", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool receiveYuanBao
    {
      get { return _receiveYuanBao?? default(bool); }
      set { _receiveYuanBao = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool receiveYuanBaoSpecified
    {
      get { return _receiveYuanBao != null; }
      set { if (value == (_receiveYuanBao== null)) _receiveYuanBao = value ? receiveYuanBao : (bool?)null; }
    }
    private bool ShouldSerializereceiveYuanBao() { return receiveYuanBaoSpecified; }
    private void ResetreceiveYuanBao() { receiveYuanBaoSpecified = false; }
    

    private long? _lastAddNumTime;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"lastAddNumTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long lastAddNumTime
    {
      get { return _lastAddNumTime?? default(long); }
      set { _lastAddNumTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool lastAddNumTimeSpecified
    {
      get { return _lastAddNumTime != null; }
      set { if (value == (_lastAddNumTime== null)) _lastAddNumTime = value ? lastAddNumTime : (long?)null; }
    }
    private bool ShouldSerializelastAddNumTime() { return lastAddNumTimeSpecified; }
    private void ResetlastAddNumTime() { lastAddNumTimeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HeroIdMsg")]
  public partial class HeroIdMsg : global::ProtoBuf.IExtensible
  {
    public HeroIdMsg() {}
    
    private int _heroId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"heroId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int heroId
    {
      get { return _heroId; }
      set { _heroId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SummonHeroResponse")]
  public partial class SummonHeroResponse : global::ProtoBuf.IExtensible
  {
    public SummonHeroResponse() {}
    
    private long _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long id
    {
      get { return _id; }
      set { _id = value; }
    }
    private hero.HeroInfo _heroInfo;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"heroInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public hero.HeroInfo heroInfo
    {
      get { return _heroInfo; }
      set { _heroInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HeroRestResponse")]
  public partial class HeroRestResponse : global::ProtoBuf.IExtensible
  {
    public HeroRestResponse() {}
    
    private long _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _heroId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"heroId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int heroId
    {
      get { return _heroId; }
      set { _heroId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}