//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: MapEditor.proto
namespace MapEditor
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Info")]
  public partial class Info : global::ProtoBuf.IExtensible
  {
    public Info() {}
    

    private int? _Coord;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Coord", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Coord
    {
      get { return _Coord?? default(int); }
      set { _Coord = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool CoordSpecified
    {
      get { return _Coord != null; }
      set { if (value == (_Coord== null)) _Coord = value ? Coord : (int?)null; }
    }
    private bool ShouldSerializeCoord() { return CoordSpecified; }
    private void ResetCoord() { CoordSpecified = false; }
    

    private int? _Type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Type
    {
      get { return _Type?? default(int); }
      set { _Type = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool TypeSpecified
    {
      get { return _Type != null; }
      set { if (value == (_Type== null)) _Type = value ? Type : (int?)null; }
    }
    private bool ShouldSerializeType() { return TypeSpecified; }
    private void ResetType() { TypeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapInfoList")]
  public partial class MapInfoList : global::ProtoBuf.IExtensible
  {
    public MapInfoList() {}
    
    private readonly global::System.Collections.Generic.List<Info> _grid = new global::System.Collections.Generic.List<Info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"grid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Info> grid
    {
      get { return _grid; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"CellType")]
    public enum CellType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Normal", Value=0)]
      Normal = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Resistance", Value=1)]
      Resistance = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Lucency", Value=2)]
      Lucency = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Protect", Value=3)]
      Protect = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Born", Value=4)]
      Born = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"P_Block", Value=6)]
      P_Block = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"P_Block_Shadow", Value=7)]
      P_Block_Shadow = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Resurgence", Value=8)]
      Resurgence = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SafeEffectPoint", Value=9)]
      SafeEffectPoint = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Separate", Value=10)]
      Separate = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Special_1", Value=11)]
      Special_1 = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Special_2", Value=12)]
      Special_2 = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Special_3", Value=13)]
      Special_3 = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Special_4", Value=14)]
      Special_4 = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Special_5", Value=15)]
      Special_5 = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Special_6", Value=16)]
      Special_6 = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Special_7", Value=17)]
      Special_7 = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Special_8", Value=18)]
      Special_8 = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Separate_1", Value=19)]
      Separate_1 = 19
    }
  
}