//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: Mining.proto
namespace mining
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MiningResponse")]
  public partial class MiningResponse : global::ProtoBuf.IExtensible
  {
    public MiningResponse() {}
    
    private long _nextTime;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nextTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long nextTime
    {
      get { return _nextTime; }
      set { _nextTime = value; }
    }
    private int _totalTimeToday;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"totalTimeToday", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int totalTimeToday
    {
      get { return _totalTimeToday; }
      set { _totalTimeToday = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SetIsAutoSellMineRequest")]
  public partial class SetIsAutoSellMineRequest : global::ProtoBuf.IExtensible
  {
    public SetIsAutoSellMineRequest() {}
    
    private bool _autoSell;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"autoSell", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool autoSell
    {
      get { return _autoSell; }
      set { _autoSell = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}