//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: OpenServerActivity.proto
namespace openServerActivity
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ExpRefineMsg")]
  public partial class ExpRefineMsg : global::ProtoBuf.IExtensible
  {
    public ExpRefineMsg() {}
    
    private int _number;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int number
    {
      get { return _number; }
      set { _number = value; }
    }
    private int _level;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DrawActivityRequest")]
  public partial class DrawActivityRequest : global::ProtoBuf.IExtensible
  {
    public DrawActivityRequest() {}
    
    private int _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActivityRequest")]
  public partial class ActivityRequest : global::ProtoBuf.IExtensible
  {
    public ActivityRequest() {}
    
    private int _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _mainId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"mainId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mainId
    {
      get { return _mainId; }
      set { _mainId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PersonalDrawInfo")]
  public partial class PersonalDrawInfo : global::ProtoBuf.IExtensible
  {
    public PersonalDrawInfo() {}
    
    private int _mainId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mainId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mainId
    {
      get { return _mainId; }
      set { _mainId = value; }
    }
    private readonly global::System.Collections.Generic.List<long> _serverInfo = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(2, Name=@"serverInfo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<long> serverInfo
    {
      get { return _serverInfo; }
    }
  
    private readonly global::System.Collections.Generic.List<long> _bossInfo = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(3, Name=@"bossInfo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<long> bossInfo
    {
      get { return _bossInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActivityCase")]
  public partial class ActivityCase : global::ProtoBuf.IExtensible
  {
    public ActivityCase() {}
    
    private readonly global::System.Collections.Generic.List<int> _mainId = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"mainId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<int> mainId
    {
      get { return _mainId; }
    }
  

    private int? _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type?? default(int); }
      set { _type = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool typeSpecified
    {
      get { return _type != null; }
      set { if (value == (_type== null)) _type = value ? type : (int?)null; }
    }
    private bool ShouldSerializetype() { return typeSpecified; }
    private void Resettype() { typeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActivityOpenMsgRequest")]
  public partial class ActivityOpenMsgRequest : global::ProtoBuf.IExtensible
  {
    public ActivityOpenMsgRequest() {}
    
    private int _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActivityUnionInfo")]
  public partial class ActivityUnionInfo : global::ProtoBuf.IExtensible
  {
    public ActivityUnionInfo() {}
    

    private int? _member;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"member", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int member
    {
      get { return _member?? default(int); }
      set { _member = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool memberSpecified
    {
      get { return _member != null; }
      set { if (value == (_member== null)) _member = value ? member : (int?)null; }
    }
    private bool ShouldSerializemember() { return memberSpecified; }
    private void Resetmember() { memberSpecified = false; }
    

    private int? _elder;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"elder", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int elder
    {
      get { return _elder?? default(int); }
      set { _elder = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool elderSpecified
    {
      get { return _elder != null; }
      set { if (value == (_elder== null)) _elder = value ? elder : (int?)null; }
    }
    private bool ShouldSerializeelder() { return elderSpecified; }
    private void Resetelder() { elderSpecified = false; }
    

    private int? _viceNum;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"viceNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int viceNum
    {
      get { return _viceNum?? default(int); }
      set { _viceNum = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool viceNumSpecified
    {
      get { return _viceNum != null; }
      set { if (value == (_viceNum== null)) _viceNum = value ? viceNum : (int?)null; }
    }
    private bool ShouldSerializeviceNum() { return viceNumSpecified; }
    private void ResetviceNum() { viceNumSpecified = false; }
    

    private long? _creater;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"creater", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long creater
    {
      get { return _creater?? default(long); }
      set { _creater = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool createrSpecified
    {
      get { return _creater != null; }
      set { if (value == (_creater== null)) _creater = value ? creater : (long?)null; }
    }
    private bool ShouldSerializecreater() { return createrSpecified; }
    private void Resetcreater() { createrSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}