//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: Rank.proto
namespace rank
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoleRank")]
  public partial class RoleRank : global::ProtoBuf.IExtensible
  {
    public RoleRank() {}
    
    private long _roleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private string _unionName;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"unionName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string unionName
    {
      get { return _unionName?? ""; }
      set { _unionName = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool unionNameSpecified
    {
      get { return _unionName != null; }
      set { if (value == (_unionName== null)) _unionName = value ? unionName : (string)null; }
    }
    private bool ShouldSerializeunionName() { return unionNameSpecified; }
    private void ResetunionName() { unionNameSpecified = false; }
    
    private int _sex;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private int _career;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"career", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int career
    {
      get { return _career; }
      set { _career = value; }
    }

    private int? _rein;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"rein", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rein
    {
      get { return _rein?? default(int); }
      set { _rein = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool reinSpecified
    {
      get { return _rein != null; }
      set { if (value == (_rein== null)) _rein = value ? rein : (int?)null; }
    }
    private bool ShouldSerializerein() { return reinSpecified; }
    private void Resetrein() { reinSpecified = false; }
    

    private int? _level;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level?? default(int); }
      set { _level = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool levelSpecified
    {
      get { return _level != null; }
      set { if (value == (_level== null)) _level = value ? level : (int?)null; }
    }
    private bool ShouldSerializelevel() { return levelSpecified; }
    private void Resetlevel() { levelSpecified = false; }
    

    private int? _nbValue;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"nbValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nbValue
    {
      get { return _nbValue?? default(int); }
      set { _nbValue = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool nbValueSpecified
    {
      get { return _nbValue != null; }
      set { if (value == (_nbValue== null)) _nbValue = value ? nbValue : (int?)null; }
    }
    private bool ShouldSerializenbValue() { return nbValueSpecified; }
    private void ResetnbValue() { nbValueSpecified = false; }
    

    private int? _office;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"office", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int office
    {
      get { return _office?? default(int); }
      set { _office = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool officeSpecified
    {
      get { return _office != null; }
      set { if (value == (_office== null)) _office = value ? office : (int?)null; }
    }
    private bool ShouldSerializeoffice() { return officeSpecified; }
    private void Resetoffice() { officeSpecified = false; }
    

    private int? _shengwang;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"shengwang", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int shengwang
    {
      get { return _shengwang?? default(int); }
      set { _shengwang = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool shengwangSpecified
    {
      get { return _shengwang != null; }
      set { if (value == (_shengwang== null)) _shengwang = value ? shengwang : (int?)null; }
    }
    private bool ShouldSerializeshengwang() { return shengwangSpecified; }
    private void Resetshengwang() { shengwangSpecified = false; }
    

    private int? _rank;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rank
    {
      get { return _rank?? default(int); }
      set { _rank = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool rankSpecified
    {
      get { return _rank != null; }
      set { if (value == (_rank== null)) _rank = value ? rank : (int?)null; }
    }
    private bool ShouldSerializerank() { return rankSpecified; }
    private void Resetrank() { rankSpecified = false; }
    

    private int? _vip;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"vip", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int vip
    {
      get { return _vip?? default(int); }
      set { _vip = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool vipSpecified
    {
      get { return _vip != null; }
      set { if (value == (_vip== null)) _vip = value ? vip : (int?)null; }
    }
    private bool ShouldSerializevip() { return vipSpecified; }
    private void Resetvip() { vipSpecified = false; }
    

    private int? _wing;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"wing", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int wing
    {
      get { return _wing?? default(int); }
      set { _wing = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool wingSpecified
    {
      get { return _wing != null; }
      set { if (value == (_wing== null)) _wing = value ? wing : (int?)null; }
    }
    private bool ShouldSerializewing() { return wingSpecified; }
    private void Resetwing() { wingSpecified = false; }
    

    private int? _equip;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"equip", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int equip
    {
      get { return _equip?? default(int); }
      set { _equip = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool equipSpecified
    {
      get { return _equip != null; }
      set { if (value == (_equip== null)) _equip = value ? equip : (int?)null; }
    }
    private bool ShouldSerializeequip() { return equipSpecified; }
    private void Resetequip() { equipSpecified = false; }
    

    private int? _card;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int card
    {
      get { return _card?? default(int); }
      set { _card = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool cardSpecified
    {
      get { return _card != null; }
      set { if (value == (_card== null)) _card = value ? card : (int?)null; }
    }
    private bool ShouldSerializecard() { return cardSpecified; }
    private void Resetcard() { cardSpecified = false; }
    

    private int? _jade;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"jade", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int jade
    {
      get { return _jade?? default(int); }
      set { _jade = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool jadeSpecified
    {
      get { return _jade != null; }
      set { if (value == (_jade== null)) _jade = value ? jade : (int?)null; }
    }
    private bool ShouldSerializejade() { return jadeSpecified; }
    private void Resetjade() { jadeSpecified = false; }
    

    private int? _honor;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"honor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int honor
    {
      get { return _honor?? default(int); }
      set { _honor = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool honorSpecified
    {
      get { return _honor != null; }
      set { if (value == (_honor== null)) _honor = value ? honor : (int?)null; }
    }
    private bool ShouldSerializehonor() { return honorSpecified; }
    private void Resethonor() { honorSpecified = false; }
    

    private int? _energy;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"energy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int energy
    {
      get { return _energy?? default(int); }
      set { _energy = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool energySpecified
    {
      get { return _energy != null; }
      set { if (value == (_energy== null)) _energy = value ? energy : (int?)null; }
    }
    private bool ShouldSerializeenergy() { return energySpecified; }
    private void Resetenergy() { energySpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UnionRank")]
  public partial class UnionRank : global::ProtoBuf.IExtensible
  {
    public UnionRank() {}
    
    private long _unionId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"unionId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long unionId
    {
      get { return _unionId; }
      set { _unionId = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _level;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private long _money;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long money
    {
      get { return _money; }
      set { _money = value; }
    }
    private long _leaderId;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"leaderId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long leaderId
    {
      get { return _leaderId; }
      set { _leaderId = value; }
    }
    private int _size;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"size", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int size
    {
      get { return _size; }
      set { _size = value; }
    }

    private int? _rank;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rank
    {
      get { return _rank?? default(int); }
      set { _rank = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool rankSpecified
    {
      get { return _rank != null; }
      set { if (value == (_rank== null)) _rank = value ? rank : (int?)null; }
    }
    private bool ShouldSerializerank() { return rankSpecified; }
    private void Resetrank() { rankSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetRankRequest")]
  public partial class GetRankRequest : global::ProtoBuf.IExtensible
  {
    public GetRankRequest() {}
    
    private rank.RankTable _table;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"table", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public rank.RankTable table
    {
      get { return _table; }
      set { _table = value; }
    }

    private int? _career;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"career", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int career
    {
      get { return _career?? default(int); }
      set { _career = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool careerSpecified
    {
      get { return _career != null; }
      set { if (value == (_career== null)) _career = value ? career : (int?)null; }
    }
    private bool ShouldSerializecareer() { return careerSpecified; }
    private void Resetcareer() { careerSpecified = false; }
    

    private int? _page;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"page", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int page
    {
      get { return _page?? default(int); }
      set { _page = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool pageSpecified
    {
      get { return _page != null; }
      set { if (value == (_page== null)) _page = value ? page : (int?)null; }
    }
    private bool ShouldSerializepage() { return pageSpecified; }
    private void Resetpage() { pageSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoleRankResponse")]
  public partial class RoleRankResponse : global::ProtoBuf.IExtensible
  {
    public RoleRankResponse() {}
    
    private rank.RankTable _table;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"table", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public rank.RankTable table
    {
      get { return _table; }
      set { _table = value; }
    }
    private readonly global::System.Collections.Generic.List<rank.RoleRank> _info = new global::System.Collections.Generic.List<rank.RoleRank>();
    [global::ProtoBuf.ProtoMember(2, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<rank.RoleRank> info
    {
      get { return _info; }
    }
  
    private int _career;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"career", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int career
    {
      get { return _career; }
      set { _career = value; }
    }
    private int _page;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"page", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int page
    {
      get { return _page; }
      set { _page = value; }
    }

    private rank.RoleRank _myInfo = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"myInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public rank.RoleRank myInfo
    {
      get { return _myInfo; }
      set { _myInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UnionRankResponse")]
  public partial class UnionRankResponse : global::ProtoBuf.IExtensible
  {
    public UnionRankResponse() {}
    
    private readonly global::System.Collections.Generic.List<rank.UnionRank> _info = new global::System.Collections.Generic.List<rank.UnionRank>();
    [global::ProtoBuf.ProtoMember(1, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<rank.UnionRank> info
    {
      get { return _info; }
    }
  
    private int _page;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"page", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int page
    {
      get { return _page; }
      set { _page = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChampionResponse")]
  public partial class ChampionResponse : global::ProtoBuf.IExtensible
  {
    public ChampionResponse() {}
    

    private rank.RoleRank _champion = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"champion", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public rank.RoleRank champion
    {
      get { return _champion; }
      set { _champion = value; }
    }

    private rank.RoleRank _zhanshi = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"zhanshi", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public rank.RoleRank zhanshi
    {
      get { return _zhanshi; }
      set { _zhanshi = value; }
    }

    private rank.RoleRank _daoshi = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"daoshi", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public rank.RoleRank daoshi
    {
      get { return _daoshi; }
      set { _daoshi = value; }
    }

    private rank.RoleRank _fashi = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"fashi", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public rank.RoleRank fashi
    {
      get { return _fashi; }
      set { _fashi = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"RankTable")]
    public enum RankTable
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NbValue", Value=1)]
      NbValue = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Level", Value=2)]
      Level = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Office", Value=3)]
      Office = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Union", Value=4)]
      Union = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Champion", Value=5)]
      Champion = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Wing", Value=6)]
      Wing = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Equip", Value=7)]
      Equip = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Jade", Value=8)]
      Jade = 8
    }
  
}