//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: RedBag.proto
namespace redBag
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RedBagDonateRequest")]
  public partial class RedBagDonateRequest : global::ProtoBuf.IExtensible
  {
    public RedBagDonateRequest() {}
    
    private int _money;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int money
    {
      get { return _money; }
      set { _money = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RedBagInfo")]
  public partial class RedBagInfo : global::ProtoBuf.IExtensible
  {
    public RedBagInfo() {}
    

    private int? _moneyPool;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"moneyPool", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int moneyPool
    {
      get { return _moneyPool?? default(int); }
      set { _moneyPool = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool moneyPoolSpecified
    {
      get { return _moneyPool != null; }
      set { if (value == (_moneyPool== null)) _moneyPool = value ? moneyPool : (int?)null; }
    }
    private bool ShouldSerializemoneyPool() { return moneyPoolSpecified; }
    private void ResetmoneyPool() { moneyPoolSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<string> _history = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"history", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> history
    {
      get { return _history; }
    }
  
    private readonly global::System.Collections.Generic.List<redBag.RedBagRankInfo> _ranks = new global::System.Collections.Generic.List<redBag.RedBagRankInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"ranks", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<redBag.RedBagRankInfo> ranks
    {
      get { return _ranks; }
    }
  

    private redBag.SelfRedBagInfo _selfInfo = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"selfInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public redBag.SelfRedBagInfo selfInfo
    {
      get { return _selfInfo; }
      set { _selfInfo = value; }
    }

    private int? _getMoney;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"getMoney", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int getMoney
    {
      get { return _getMoney?? default(int); }
      set { _getMoney = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool getMoneySpecified
    {
      get { return _getMoney != null; }
      set { if (value == (_getMoney== null)) _getMoney = value ? getMoney : (int?)null; }
    }
    private bool ShouldSerializegetMoney() { return getMoneySpecified; }
    private void ResetgetMoney() { getMoneySpecified = false; }
    

    private redBag.SendRoleInfo _sendRole = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"sendRole", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public redBag.SendRoleInfo sendRole
    {
      get { return _sendRole; }
      set { _sendRole = value; }
    }

    private bool? _haveFirstGet;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"haveFirstGet", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool haveFirstGet
    {
      get { return _haveFirstGet?? default(bool); }
      set { _haveFirstGet = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool haveFirstGetSpecified
    {
      get { return _haveFirstGet != null; }
      set { if (value == (_haveFirstGet== null)) _haveFirstGet = value ? haveFirstGet : (bool?)null; }
    }
    private bool ShouldSerializehaveFirstGet() { return haveFirstGetSpecified; }
    private void ResethaveFirstGet() { haveFirstGetSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SelfRedBagInfo")]
  public partial class SelfRedBagInfo : global::ProtoBuf.IExtensible
  {
    public SelfRedBagInfo() {}
    

    private int? _money;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int money
    {
      get { return _money?? default(int); }
      set { _money = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool moneySpecified
    {
      get { return _money != null; }
      set { if (value == (_money== null)) _money = value ? money : (int?)null; }
    }
    private bool ShouldSerializemoney() { return moneySpecified; }
    private void Resetmoney() { moneySpecified = false; }
    

    private int? _rank;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rank
    {
      get { return _rank?? default(int); }
      set { _rank = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool rankSpecified
    {
      get { return _rank != null; }
      set { if (value == (_rank== null)) _rank = value ? rank : (int?)null; }
    }
    private bool ShouldSerializerank() { return rankSpecified; }
    private void Resetrank() { rankSpecified = false; }
    
    private int _getTimes;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"getTimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int getTimes
    {
      get { return _getTimes; }
      set { _getTimes = value; }
    }
    private long _lastTime;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"lastTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long lastTime
    {
      get { return _lastTime; }
      set { _lastTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RedBagRankInfo")]
  public partial class RedBagRankInfo : global::ProtoBuf.IExtensible
  {
    public RedBagRankInfo() {}
    

    private int? _rank;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rank
    {
      get { return _rank?? default(int); }
      set { _rank = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool rankSpecified
    {
      get { return _rank != null; }
      set { if (value == (_rank== null)) _rank = value ? rank : (int?)null; }
    }
    private bool ShouldSerializerank() { return rankSpecified; }
    private void Resetrank() { rankSpecified = false; }
    

    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name?? ""; }
      set { _name = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool nameSpecified
    {
      get { return _name != null; }
      set { if (value == (_name== null)) _name = value ? name : (string)null; }
    }
    private bool ShouldSerializename() { return nameSpecified; }
    private void Resetname() { nameSpecified = false; }
    

    private int? _money;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int money
    {
      get { return _money?? default(int); }
      set { _money = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool moneySpecified
    {
      get { return _money != null; }
      set { if (value == (_money== null)) _money = value ? money : (int?)null; }
    }
    private bool ShouldSerializemoney() { return moneySpecified; }
    private void Resetmoney() { moneySpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SendRoleInfo")]
  public partial class SendRoleInfo : global::ProtoBuf.IExtensible
  {
    public SendRoleInfo() {}
    

    private long? _roleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long roleId
    {
      get { return _roleId?? default(long); }
      set { _roleId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool roleIdSpecified
    {
      get { return _roleId != null; }
      set { if (value == (_roleId== null)) _roleId = value ? roleId : (long?)null; }
    }
    private bool ShouldSerializeroleId() { return roleIdSpecified; }
    private void ResetroleId() { roleIdSpecified = false; }
    

    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name?? ""; }
      set { _name = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool nameSpecified
    {
      get { return _name != null; }
      set { if (value == (_name== null)) _name = value ? name : (string)null; }
    }
    private bool ShouldSerializename() { return nameSpecified; }
    private void Resetname() { nameSpecified = false; }
    

    private int? _career;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"career", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int career
    {
      get { return _career?? default(int); }
      set { _career = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool careerSpecified
    {
      get { return _career != null; }
      set { if (value == (_career== null)) _career = value ? career : (int?)null; }
    }
    private bool ShouldSerializecareer() { return careerSpecified; }
    private void Resetcareer() { careerSpecified = false; }
    

    private int? _sex;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sex
    {
      get { return _sex?? default(int); }
      set { _sex = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool sexSpecified
    {
      get { return _sex != null; }
      set { if (value == (_sex== null)) _sex = value ? sex : (int?)null; }
    }
    private bool ShouldSerializesex() { return sexSpecified; }
    private void Resetsex() { sexSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}