//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: ShareServer2.proto
namespace shareserver2
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChangeLineReq")]
  public partial class ChangeLineReq : global::ProtoBuf.IExtensible
  {
    public ChangeLineReq() {}
    
    private int _targetServerType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"targetServerType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int targetServerType
    {
      get { return _targetServerType; }
      set { _targetServerType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChangeLine")]
  public partial class ChangeLine : global::ProtoBuf.IExtensible
  {
    public ChangeLine() {}
    
    private long _userId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private long _roleId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private int _sourceServerId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"sourceServerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sourceServerId
    {
      get { return _sourceServerId; }
      set { _sourceServerId = value; }
    }
    private int _targetServerId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"targetServerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int targetServerId
    {
      get { return _targetServerId; }
      set { _targetServerId = value; }
    }
    private int _targetServerType;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"targetServerType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int targetServerType
    {
      get { return _targetServerType; }
      set { _targetServerType = value; }
    }
    private string _sign;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"sign", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sign
    {
      get { return _sign; }
      set { _sign = value; }
    }

    private bool? _reconnect;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"reconnect", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool reconnect
    {
      get { return _reconnect?? default(bool); }
      set { _reconnect = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool reconnectSpecified
    {
      get { return _reconnect != null; }
      set { if (value == (_reconnect== null)) _reconnect = value ? reconnect : (bool?)null; }
    }
    private bool ShouldSerializereconnect() { return reconnectSpecified; }
    private void Resetreconnect() { reconnectSpecified = false; }
    

    private string _targetServerIp;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"targetServerIp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string targetServerIp
    {
      get { return _targetServerIp?? ""; }
      set { _targetServerIp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool targetServerIpSpecified
    {
      get { return _targetServerIp != null; }
      set { if (value == (_targetServerIp== null)) _targetServerIp = value ? targetServerIp : (string)null; }
    }
    private bool ShouldSerializetargetServerIp() { return targetServerIpSpecified; }
    private void ResettargetServerIp() { targetServerIpSpecified = false; }
    

    private int? _targetServerPort;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"targetServerPort", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int targetServerPort
    {
      get { return _targetServerPort?? default(int); }
      set { _targetServerPort = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool targetServerPortSpecified
    {
      get { return _targetServerPort != null; }
      set { if (value == (_targetServerPort== null)) _targetServerPort = value ? targetServerPort : (int?)null; }
    }
    private bool ShouldSerializetargetServerPort() { return targetServerPortSpecified; }
    private void ResettargetServerPort() { targetServerPortSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MagicNodeChangeInfo")]
  public partial class MagicNodeChangeInfo : global::ProtoBuf.IExtensible
  {
    public MagicNodeChangeInfo() {}
    

    private int? _num;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num
    {
      get { return _num?? default(int); }
      set { _num = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool numSpecified
    {
      get { return _num != null; }
      set { if (value == (_num== null)) _num = value ? num : (int?)null; }
    }
    private bool ShouldSerializenum() { return numSpecified; }
    private void Resetnum() { numSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<shareserver2.MagicNodeMonsterInfo> _monsterInfo = new global::System.Collections.Generic.List<shareserver2.MagicNodeMonsterInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"monsterInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<shareserver2.MagicNodeMonsterInfo> monsterInfo
    {
      get { return _monsterInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SumbitGodStoneReq")]
  public partial class SumbitGodStoneReq : global::ProtoBuf.IExtensible
  {
    public SumbitGodStoneReq() {}
    

    private int? _num;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num
    {
      get { return _num?? default(int); }
      set { _num = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool numSpecified
    {
      get { return _num != null; }
      set { if (value == (_num== null)) _num = value ? num : (int?)null; }
    }
    private bool ShouldSerializenum() { return numSpecified; }
    private void Resetnum() { numSpecified = false; }
    

    private bool? _confirm;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"confirm", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool confirm
    {
      get { return _confirm?? default(bool); }
      set { _confirm = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool confirmSpecified
    {
      get { return _confirm != null; }
      set { if (value == (_confirm== null)) _confirm = value ? confirm : (bool?)null; }
    }
    private bool ShouldSerializeconfirm() { return confirmSpecified; }
    private void Resetconfirm() { confirmSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SumbitGodStoneRes")]
  public partial class SumbitGodStoneRes : global::ProtoBuf.IExtensible
  {
    public SumbitGodStoneRes() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MagicNodeMonsterInfo")]
  public partial class MagicNodeMonsterInfo : global::ProtoBuf.IExtensible
  {
    public MagicNodeMonsterInfo() {}
    

    private int? _monsterId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"monsterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int monsterId
    {
      get { return _monsterId?? default(int); }
      set { _monsterId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool monsterIdSpecified
    {
      get { return _monsterId != null; }
      set { if (value == (_monsterId== null)) _monsterId = value ? monsterId : (int?)null; }
    }
    private bool ShouldSerializemonsterId() { return monsterIdSpecified; }
    private void ResetmonsterId() { monsterIdSpecified = false; }
    

    private int? _state;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int state
    {
      get { return _state?? default(int); }
      set { _state = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool stateSpecified
    {
      get { return _state != null; }
      set { if (value == (_state== null)) _state = value ? state : (int?)null; }
    }
    private bool ShouldSerializestate() { return stateSpecified; }
    private void Resetstate() { stateSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BulletinToTargetServer")]
  public partial class BulletinToTargetServer : global::ProtoBuf.IExtensible
  {
    public BulletinToTargetServer() {}
    

    private int? _BulletinConfigId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"BulletinConfigId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int BulletinConfigId
    {
      get { return _BulletinConfigId?? default(int); }
      set { _BulletinConfigId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool BulletinConfigIdSpecified
    {
      get { return _BulletinConfigId != null; }
      set { if (value == (_BulletinConfigId== null)) _BulletinConfigId = value ? BulletinConfigId : (int?)null; }
    }
    private bool ShouldSerializeBulletinConfigId() { return BulletinConfigIdSpecified; }
    private void ResetBulletinConfigId() { BulletinConfigIdSpecified = false; }
    

    private string _args1;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"args1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string args1
    {
      get { return _args1?? ""; }
      set { _args1 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool args1Specified
    {
      get { return _args1 != null; }
      set { if (value == (_args1== null)) _args1 = value ? args1 : (string)null; }
    }
    private bool ShouldSerializeargs1() { return args1Specified; }
    private void Resetargs1() { args1Specified = false; }
    

    private string _args2;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"args2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string args2
    {
      get { return _args2?? ""; }
      set { _args2 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool args2Specified
    {
      get { return _args2 != null; }
      set { if (value == (_args2== null)) _args2 = value ? args2 : (string)null; }
    }
    private bool ShouldSerializeargs2() { return args2Specified; }
    private void Resetargs2() { args2Specified = false; }
    

    private string _args3;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"args3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string args3
    {
      get { return _args3?? ""; }
      set { _args3 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool args3Specified
    {
      get { return _args3 != null; }
      set { if (value == (_args3== null)) _args3 = value ? args3 : (string)null; }
    }
    private bool ShouldSerializeargs3() { return args3Specified; }
    private void Resetargs3() { args3Specified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SLDGGiftMsg")]
  public partial class SLDGGiftMsg : global::ProtoBuf.IExtensible
  {
    public SLDGGiftMsg() {}
    

    private long? _time;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long time
    {
      get { return _time?? default(long); }
      set { _time = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool timeSpecified
    {
      get { return _time != null; }
      set { if (value == (_time== null)) _time = value ? time : (long?)null; }
    }
    private bool ShouldSerializetime() { return timeSpecified; }
    private void Resettime() { timeSpecified = false; }
    

    private bool? _isBuy;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"isBuy", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isBuy
    {
      get { return _isBuy?? default(bool); }
      set { _isBuy = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool isBuySpecified
    {
      get { return _isBuy != null; }
      set { if (value == (_isBuy== null)) _isBuy = value ? isBuy : (bool?)null; }
    }
    private bool ShouldSerializeisBuy() { return isBuySpecified; }
    private void ResetisBuy() { isBuySpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}