//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: Stone.proto
// Note: requires additional types generated from: Bag.proto
namespace stone
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChangeStoneRequest")]
  public partial class ChangeStoneRequest : global::ProtoBuf.IExtensible
  {
    public ChangeStoneRequest() {}
    

    private int? _position;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int position
    {
      get { return _position?? default(int); }
      set { _position = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool positionSpecified
    {
      get { return _position != null; }
      set { if (value == (_position== null)) _position = value ? position : (int?)null; }
    }
    private bool ShouldSerializeposition() { return positionSpecified; }
    private void Resetposition() { positionSpecified = false; }
    
    private int _order;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"order", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int order
    {
      get { return _order; }
      set { _order = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }

    private int? _bagIndex;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"bagIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bagIndex
    {
      get { return _bagIndex?? default(int); }
      set { _bagIndex = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool bagIndexSpecified
    {
      get { return _bagIndex != null; }
      set { if (value == (_bagIndex== null)) _bagIndex = value ? bagIndex : (int?)null; }
    }
    private bool ShouldSerializebagIndex() { return bagIndexSpecified; }
    private void ResetbagIndex() { bagIndexSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChangeStoneResponse")]
  public partial class ChangeStoneResponse : global::ProtoBuf.IExtensible
  {
    public ChangeStoneResponse() {}
    
    private stone.EveryStoneInfo _everyStoneInfo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"everyStoneInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public stone.EveryStoneInfo everyStoneInfo
    {
      get { return _everyStoneInfo; }
      set { _everyStoneInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OrderStoneOpenMsg")]
  public partial class OrderStoneOpenMsg : global::ProtoBuf.IExtensible
  {
    public OrderStoneOpenMsg() {}
    
    private readonly global::System.Collections.Generic.List<stone.OrderStoneMsg> _stoneList = new global::System.Collections.Generic.List<stone.OrderStoneMsg>();
    [global::ProtoBuf.ProtoMember(1, Name=@"stoneList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<stone.OrderStoneMsg> stoneList
    {
      get { return _stoneList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OrderStoneRequest")]
  public partial class OrderStoneRequest : global::ProtoBuf.IExtensible
  {
    public OrderStoneRequest() {}
    
    private int _order;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"order", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int order
    {
      get { return _order; }
      set { _order = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OrderStoneMsg")]
  public partial class OrderStoneMsg : global::ProtoBuf.IExtensible
  {
    public OrderStoneMsg() {}
    
    private int _order;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"order", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int order
    {
      get { return _order; }
      set { _order = value; }
    }
    private readonly global::System.Collections.Generic.List<stone.EveryStoneInfo> _Infos = new global::System.Collections.Generic.List<stone.EveryStoneInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"Infos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<stone.EveryStoneInfo> Infos
    {
      get { return _Infos; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EveryStoneInfo")]
  public partial class EveryStoneInfo : global::ProtoBuf.IExtensible
  {
    public EveryStoneInfo() {}
    
    private int _position;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int position
    {
      get { return _position; }
      set { _position = value; }
    }

    private bag.BagItemInfo _Stone = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Stone", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bag.BagItemInfo Stone
    {
      get { return _Stone; }
      set { _Stone = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StoneItemChangeList")]
  public partial class StoneItemChangeList : global::ProtoBuf.IExtensible
  {
    public StoneItemChangeList() {}
    
    private readonly global::System.Collections.Generic.List<bag.BagItemInfo> _changeList = new global::System.Collections.Generic.List<bag.BagItemInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"changeList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bag.BagItemInfo> changeList
    {
      get { return _changeList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CombineStoneRequest")]
  public partial class CombineStoneRequest : global::ProtoBuf.IExtensible
  {
    public CombineStoneRequest() {}
    
    private int _lv;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int lv
    {
      get { return _lv; }
      set { _lv = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StoneCallBackRequest")]
  public partial class StoneCallBackRequest : global::ProtoBuf.IExtensible
  {
    public StoneCallBackRequest() {}
    
    private readonly global::System.Collections.Generic.List<int> _indexList = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"indexList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> indexList
    {
      get { return _indexList; }
    }
  

    private int? _stoneLv;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"stoneLv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int stoneLv
    {
      get { return _stoneLv?? default(int); }
      set { _stoneLv = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool stoneLvSpecified
    {
      get { return _stoneLv != null; }
      set { if (value == (_stoneLv== null)) _stoneLv = value ? stoneLv : (int?)null; }
    }
    private bool ShouldSerializestoneLv() { return stoneLvSpecified; }
    private void ResetstoneLv() { stoneLvSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StoneCallBackIndexResponse")]
  public partial class StoneCallBackIndexResponse : global::ProtoBuf.IExtensible
  {
    public StoneCallBackIndexResponse() {}
    
    private readonly global::System.Collections.Generic.List<int> _indexList = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"indexList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> indexList
    {
      get { return _indexList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}