//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: Storehouse.proto
// Note: requires additional types generated from: Bag.proto
namespace storehouse
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StorehouseInfo")]
  public partial class StorehouseInfo : global::ProtoBuf.IExtensible
  {
    public StorehouseInfo() {}
    
    private readonly global::System.Collections.Generic.List<bag.BagItemInfo> _itemInfo = new global::System.Collections.Generic.List<bag.BagItemInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"itemInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bag.BagItemInfo> itemInfo
    {
      get { return _itemInfo; }
    }
  

    private int? _maxCount;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"maxCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maxCount
    {
      get { return _maxCount?? default(int); }
      set { _maxCount = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool maxCountSpecified
    {
      get { return _maxCount != null; }
      set { if (value == (_maxCount== null)) _maxCount = value ? maxCount : (int?)null; }
    }
    private bool ShouldSerializemaxCount() { return maxCountSpecified; }
    private void ResetmaxCount() { maxCountSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StorehouseItemChangeList")]
  public partial class StorehouseItemChangeList : global::ProtoBuf.IExtensible
  {
    public StorehouseItemChangeList() {}
    
    private readonly global::System.Collections.Generic.List<bag.BagItemInfo> _changeList = new global::System.Collections.Generic.List<bag.BagItemInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"changeList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bag.BagItemInfo> changeList
    {
      get { return _changeList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ExchangeItemMsg")]
  public partial class ExchangeItemMsg : global::ProtoBuf.IExtensible
  {
    public ExchangeItemMsg() {}
    
    private int _fromIndex;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"fromIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fromIndex
    {
      get { return _fromIndex; }
      set { _fromIndex = value; }
    }
    private int _toIndex;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"toIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int toIndex
    {
      get { return _toIndex; }
      set { _toIndex = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StorehouseToBagRequest")]
  public partial class StorehouseToBagRequest : global::ProtoBuf.IExtensible
  {
    public StorehouseToBagRequest() {}
    
    private int _storehouseIndex;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"storehouseIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int storehouseIndex
    {
      get { return _storehouseIndex; }
      set { _storehouseIndex = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StorehouseToBagResponse")]
  public partial class StorehouseToBagResponse : global::ProtoBuf.IExtensible
  {
    public StorehouseToBagResponse() {}
    
    private readonly global::System.Collections.Generic.List<bag.BagItemInfo> _removeItem = new global::System.Collections.Generic.List<bag.BagItemInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"removeItem", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bag.BagItemInfo> removeItem
    {
      get { return _removeItem; }
    }
  
    private readonly global::System.Collections.Generic.List<bag.BagItemInfo> _addItem = new global::System.Collections.Generic.List<bag.BagItemInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"addItem", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bag.BagItemInfo> addItem
    {
      get { return _addItem; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddStorehouseRequest")]
  public partial class AddStorehouseRequest : global::ProtoBuf.IExtensible
  {
    public AddStorehouseRequest() {}
    
    private int _line;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"line", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int line
    {
      get { return _line; }
      set { _line = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddStorehouseCount")]
  public partial class AddStorehouseCount : global::ProtoBuf.IExtensible
  {
    public AddStorehouseCount() {}
    
    private int _storehouseCount;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"storehouseCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int storehouseCount
    {
      get { return _storehouseCount; }
      set { _storehouseCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}