//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: Task.proto
// Note: requires additional types generated from: Bag.proto
namespace task
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GoalInfo")]
  public partial class GoalInfo : global::ProtoBuf.IExtensible
  {
    public GoalInfo() {}
    
    private int _goalId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"goalId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int goalId
    {
      get { return _goalId; }
      set { _goalId = value; }
    }
    private int _currentCount;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"currentCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int currentCount
    {
      get { return _currentCount; }
      set { _currentCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TaskInfo")]
  public partial class TaskInfo : global::ProtoBuf.IExtensible
  {
    public TaskInfo() {}
    
    private int _taskId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"taskId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int taskId
    {
      get { return _taskId; }
      set { _taskId = value; }
    }
    private task.TaskState _state;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public task.TaskState state
    {
      get { return _state; }
      set { _state = value; }
    }
    private readonly global::System.Collections.Generic.List<task.GoalInfo> _goals = new global::System.Collections.Generic.List<task.GoalInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"goals", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<task.GoalInfo> goals
    {
      get { return _goals; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TaskList")]
  public partial class TaskList : global::ProtoBuf.IExtensible
  {
    public TaskList() {}
    
    private readonly global::System.Collections.Generic.List<task.TaskInfo> _tasks = new global::System.Collections.Generic.List<task.TaskInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"tasks", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<task.TaskInfo> tasks
    {
      get { return _tasks; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TaskGoalUpdateResponse")]
  public partial class TaskGoalUpdateResponse : global::ProtoBuf.IExtensible
  {
    public TaskGoalUpdateResponse() {}
    
    private int _taskId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"taskId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int taskId
    {
      get { return _taskId; }
      set { _taskId = value; }
    }

    private task.GoalInfo _goal = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"goal", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public task.GoalInfo goal
    {
      get { return _goal; }
      set { _goal = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TaskIdMsg")]
  public partial class TaskIdMsg : global::ProtoBuf.IExtensible
  {
    public TaskIdMsg() {}
    
    private int _taskId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"taskId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int taskId
    {
      get { return _taskId; }
      set { _taskId = value; }
    }

    private bool? _quick;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"quick", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool quick
    {
      get { return _quick?? default(bool); }
      set { _quick = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool quickSpecified
    {
      get { return _quick != null; }
      set { if (value == (_quick== null)) _quick = value ? quick : (bool?)null; }
    }
    private bool ShouldSerializequick() { return quickSpecified; }
    private void Resetquick() { quickSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SubmitTaskRequest")]
  public partial class SubmitTaskRequest : global::ProtoBuf.IExtensible
  {
    public SubmitTaskRequest() {}
    
    private int _taskId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"taskId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int taskId
    {
      get { return _taskId; }
      set { _taskId = value; }
    }

    private int? _multi;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"multi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int multi
    {
      get { return _multi?? default(int); }
      set { _multi = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool multiSpecified
    {
      get { return _multi != null; }
      set { if (value == (_multi== null)) _multi = value ? multi : (int?)null; }
    }
    private bool ShouldSerializemulti() { return multiSpecified; }
    private void Resetmulti() { multiSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SubmitTaskResponse")]
  public partial class SubmitTaskResponse : global::ProtoBuf.IExtensible
  {
    public SubmitTaskResponse() {}
    
    private int _taskId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"taskId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int taskId
    {
      get { return _taskId; }
      set { _taskId = value; }
    }
    private readonly global::System.Collections.Generic.List<bag.BagItemInfo> _changedItems = new global::System.Collections.Generic.List<bag.BagItemInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"changedItems", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bag.BagItemInfo> changedItems
    {
      get { return _changedItems; }
    }
  
    private readonly global::System.Collections.Generic.List<task.TaskInfo> _newTasks = new global::System.Collections.Generic.List<task.TaskInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"newTasks", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<task.TaskInfo> newTasks
    {
      get { return _newTasks; }
    }
  

    private int? _dailyTaskDone;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"dailyTaskDone", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dailyTaskDone
    {
      get { return _dailyTaskDone?? default(int); }
      set { _dailyTaskDone = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool dailyTaskDoneSpecified
    {
      get { return _dailyTaskDone != null; }
      set { if (value == (_dailyTaskDone== null)) _dailyTaskDone = value ? dailyTaskDone : (int?)null; }
    }
    private bool ShouldSerializedailyTaskDone() { return dailyTaskDoneSpecified; }
    private void ResetdailyTaskDone() { dailyTaskDoneSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TalkToNPCRequest")]
  public partial class TalkToNPCRequest : global::ProtoBuf.IExtensible
  {
    public TalkToNPCRequest() {}
    
    private int _npcId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"npcId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int npcId
    {
      get { return _npcId; }
      set { _npcId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FlyToGoalRequest")]
  public partial class FlyToGoalRequest : global::ProtoBuf.IExtensible
  {
    public FlyToGoalRequest() {}
    
    private int _taskId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"taskId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int taskId
    {
      get { return _taskId; }
      set { _taskId = value; }
    }

    private int? _goalId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"goalId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int goalId
    {
      get { return _goalId?? default(int); }
      set { _goalId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool goalIdSpecified
    {
      get { return _goalId != null; }
      set { if (value == (_goalId== null)) _goalId = value ? goalId : (int?)null; }
    }
    private bool ShouldSerializegoalId() { return goalIdSpecified; }
    private void ResetgoalId() { goalIdSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RefreshDailyTaskRequest")]
  public partial class RefreshDailyTaskRequest : global::ProtoBuf.IExtensible
  {
    public RefreshDailyTaskRequest() {}
    
    private bool _useYuanbao;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"useYuanbao", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool useYuanbao
    {
      get { return _useYuanbao; }
      set { _useYuanbao = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RefreshDailyTaskResponse")]
  public partial class RefreshDailyTaskResponse : global::ProtoBuf.IExtensible
  {
    public RefreshDailyTaskResponse() {}
    
    private int _oldTaskId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"oldTaskId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int oldTaskId
    {
      get { return _oldTaskId; }
      set { _oldTaskId = value; }
    }
    private readonly global::System.Collections.Generic.List<task.TaskInfo> _newTasks = new global::System.Collections.Generic.List<task.TaskInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"newTasks", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<task.TaskInfo> newTasks
    {
      get { return _newTasks; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuyDailyTaskRequest")]
  public partial class BuyDailyTaskRequest : global::ProtoBuf.IExtensible
  {
    public BuyDailyTaskRequest() {}
    
    private int _count;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RefreshDragonRewardRequest")]
  public partial class RefreshDragonRewardRequest : global::ProtoBuf.IExtensible
  {
    public RefreshDragonRewardRequest() {}
    

    private bool? _useYuanbao;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"useYuanbao", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool useYuanbao
    {
      get { return _useYuanbao?? default(bool); }
      set { _useYuanbao = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool useYuanbaoSpecified
    {
      get { return _useYuanbao != null; }
      set { if (value == (_useYuanbao== null)) _useYuanbao = value ? useYuanbao : (bool?)null; }
    }
    private bool ShouldSerializeuseYuanbao() { return useYuanbaoSpecified; }
    private void ResetuseYuanbao() { useYuanbaoSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetDragonRewardTasksInfoRequest")]
  public partial class GetDragonRewardTasksInfoRequest : global::ProtoBuf.IExtensible
  {
    public GetDragonRewardTasksInfoRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuyDragonRewardTaskRequest")]
  public partial class BuyDragonRewardTaskRequest : global::ProtoBuf.IExtensible
  {
    public BuyDragonRewardTaskRequest() {}
    

    private int? _count;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int count
    {
      get { return _count?? default(int); }
      set { _count = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool countSpecified
    {
      get { return _count != null; }
      set { if (value == (_count== null)) _count = value ? count : (int?)null; }
    }
    private bool ShouldSerializecount() { return countSpecified; }
    private void Resetcount() { countSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GiveUpDragonRewardTasksReq")]
  public partial class GiveUpDragonRewardTasksReq : global::ProtoBuf.IExtensible
  {
    public GiveUpDragonRewardTasksReq() {}
    

    private int? _taskId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"taskId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int taskId
    {
      get { return _taskId?? default(int); }
      set { _taskId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool taskIdSpecified
    {
      get { return _taskId != null; }
      set { if (value == (_taskId== null)) _taskId = value ? taskId : (int?)null; }
    }
    private bool ShouldSerializetaskId() { return taskIdSpecified; }
    private void ResettaskId() { taskIdSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AutoFinishTaskRequest")]
  public partial class AutoFinishTaskRequest : global::ProtoBuf.IExtensible
  {
    public AutoFinishTaskRequest() {}
    

    private int? _taskId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"taskId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int taskId
    {
      get { return _taskId?? default(int); }
      set { _taskId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool taskIdSpecified
    {
      get { return _taskId != null; }
      set { if (value == (_taskId== null)) _taskId = value ? taskId : (int?)null; }
    }
    private bool ShouldSerializetaskId() { return taskIdSpecified; }
    private void ResettaskId() { taskIdSpecified = false; }
    

    private int? _count;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int count
    {
      get { return _count?? default(int); }
      set { _count = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool countSpecified
    {
      get { return _count != null; }
      set { if (value == (_count== null)) _count = value ? count : (int?)null; }
    }
    private bool ShouldSerializecount() { return countSpecified; }
    private void Resetcount() { countSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"TaskState")]
    public enum TaskState
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UnAcceptable", Value=1)]
      UnAcceptable = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Acceptable", Value=2)]
      Acceptable = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Accepted", Value=3)]
      Accepted = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Completed", Value=4)]
      Completed = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Submitted", Value=5)]
      Submitted = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Failed", Value=6)]
      Failed = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GiveUp", Value=7)]
      GiveUp = 7
    }
  
}