//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: Title.proto
namespace title
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TitleMapInfo")]
  public partial class TitleMapInfo : global::ProtoBuf.IExtensible
  {
    public TitleMapInfo() {}
    
    private readonly global::System.Collections.Generic.List<title.TitleInfo> _info = new global::System.Collections.Generic.List<title.TitleInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<title.TitleInfo> info
    {
      get { return _info; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TitleInfo")]
  public partial class TitleInfo : global::ProtoBuf.IExtensible
  {
    public TitleInfo() {}
    
    private int _TitleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"TitleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int TitleId
    {
      get { return _TitleId; }
      set { _TitleId = value; }
    }

    private long? _getTime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"getTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long getTime
    {
      get { return _getTime?? default(long); }
      set { _getTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool getTimeSpecified
    {
      get { return _getTime != null; }
      set { if (value == (_getTime== null)) _getTime = value ? getTime : (long?)null; }
    }
    private bool ShouldSerializegetTime() { return getTimeSpecified; }
    private void ResetgetTime() { getTimeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChangeTitle")]
  public partial class ChangeTitle : global::ProtoBuf.IExtensible
  {
    public ChangeTitle() {}
    
    private int _TitleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"TitleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int TitleId
    {
      get { return _TitleId; }
      set { _TitleId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}