//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: Transaction.proto
// Note: requires additional types generated from: Bag.proto
namespace transaction
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TransactionPartyInfo")]
  public partial class TransactionPartyInfo : global::ProtoBuf.IExtensible
  {
    public TransactionPartyInfo() {}
    
    private long _roleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private readonly global::System.Collections.Generic.List<bag.BagItemInfo> _items = new global::System.Collections.Generic.List<bag.BagItemInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bag.BagItemInfo> items
    {
      get { return _items; }
    }
  
    private int _gold;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private int _yuanbao;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"yuanbao", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int yuanbao
    {
      get { return _yuanbao; }
      set { _yuanbao = value; }
    }
    private bool _locked;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"locked", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool locked
    {
      get { return _locked; }
      set { _locked = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TransactionInfo")]
  public partial class TransactionInfo : global::ProtoBuf.IExtensible
  {
    public TransactionInfo() {}
    
    private readonly global::System.Collections.Generic.List<transaction.TransactionPartyInfo> _parties = new global::System.Collections.Generic.List<transaction.TransactionPartyInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"parties", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<transaction.TransactionPartyInfo> parties
    {
      get { return _parties; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ApplyTransactionMsg")]
  public partial class ApplyTransactionMsg : global::ProtoBuf.IExtensible
  {
    public ApplyTransactionMsg() {}
    
    private long _roleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ConfirmTransactionApplyRequest")]
  public partial class ConfirmTransactionApplyRequest : global::ProtoBuf.IExtensible
  {
    public ConfirmTransactionApplyRequest() {}
    
    private long _roleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private bool _accept;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"accept", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool accept
    {
      get { return _accept; }
      set { _accept = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddItemToTransactionRequest")]
  public partial class AddItemToTransactionRequest : global::ProtoBuf.IExtensible
  {
    public AddItemToTransactionRequest() {}
    
    private int _bagIndex;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"bagIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bagIndex
    {
      get { return _bagIndex; }
      set { _bagIndex = value; }
    }
    private int _count;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SetTransactionMoneyRequest")]
  public partial class SetTransactionMoneyRequest : global::ProtoBuf.IExtensible
  {
    public SetTransactionMoneyRequest() {}
    
    private int _gold;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private int _yuanbao;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"yuanbao", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int yuanbao
    {
      get { return _yuanbao; }
      set { _yuanbao = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RemoveItemFromTransactionRequest")]
  public partial class RemoveItemFromTransactionRequest : global::ProtoBuf.IExtensible
  {
    public RemoveItemFromTransactionRequest() {}
    
    private int _index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}