//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: Vip.proto
namespace vip
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VipInfo")]
  public partial class VipInfo : global::ProtoBuf.IExtensible
  {
    public VipInfo() {}
    
    private int _exp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private readonly global::System.Collections.Generic.List<long> _reward = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(2, Name=@"reward", DataFormat = global::ProtoBuf.DataFormat.TwosComplement, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<long> reward
    {
      get { return _reward; }
    }
  

    private int? _vipNumber;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"vipNumber", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int vipNumber
    {
      get { return _vipNumber?? default(int); }
      set { _vipNumber = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool vipNumberSpecified
    {
      get { return _vipNumber != null; }
      set { if (value == (_vipNumber== null)) _vipNumber = value ? vipNumber : (int?)null; }
    }
    private bool ShouldSerializevipNumber() { return vipNumberSpecified; }
    private void ResetvipNumber() { vipNumberSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DrawVipGiftPackRequest")]
  public partial class DrawVipGiftPackRequest : global::ProtoBuf.IExtensible
  {
    public DrawVipGiftPackRequest() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CardInfo")]
  public partial class CardInfo : global::ProtoBuf.IExtensible
  {
    public CardInfo() {}
    
    private int _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private long _endTime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"endTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long endTime
    {
      get { return _endTime; }
      set { _endTime = value; }
    }

    private bool? _dayReward;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"dayReward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool dayReward
    {
      get { return _dayReward?? default(bool); }
      set { _dayReward = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool dayRewardSpecified
    {
      get { return _dayReward != null; }
      set { if (value == (_dayReward== null)) _dayReward = value ? dayReward : (bool?)null; }
    }
    private bool ShouldSerializedayReward() { return dayRewardSpecified; }
    private void ResetdayReward() { dayRewardSpecified = false; }
    

    private bool? _specialCard;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"specialCard", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool specialCard
    {
      get { return _specialCard?? default(bool); }
      set { _specialCard = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool specialCardSpecified
    {
      get { return _specialCard != null; }
      set { if (value == (_specialCard== null)) _specialCard = value ? specialCard : (bool?)null; }
    }
    private bool ShouldSerializespecialCard() { return specialCardSpecified; }
    private void ResetspecialCard() { specialCardSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CardRequest")]
  public partial class CardRequest : global::ProtoBuf.IExtensible
  {
    public CardRequest() {}
    
    private int _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DrawCardGiftRequest")]
  public partial class DrawCardGiftRequest : global::ProtoBuf.IExtensible
  {
    public DrawCardGiftRequest() {}
    
    private int _cardType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"cardType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cardType
    {
      get { return _cardType; }
      set { _cardType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VipExpBuffMsg")]
  public partial class VipExpBuffMsg : global::ProtoBuf.IExtensible
  {
    public VipExpBuffMsg() {}
    
    private int _expTimes;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"expTimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int expTimes
    {
      get { return _expTimes; }
      set { _expTimes = value; }
    }
    private long _endTime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"endTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long endTime
    {
      get { return _endTime; }
      set { _endTime = value; }
    }
    private bool _draw;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"draw", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool draw
    {
      get { return _draw; }
      set { _draw = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FirstRechargeGiftMsg")]
  public partial class FirstRechargeGiftMsg : global::ProtoBuf.IExtensible
  {
    public FirstRechargeGiftMsg() {}
    
    private bool _draw;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"draw", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool draw
    {
      get { return _draw; }
      set { _draw = value; }
    }
    private int _totalNum;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"totalNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int totalNum
    {
      get { return _totalNum; }
      set { _totalNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetDayChargeAwardRequest")]
  public partial class GetDayChargeAwardRequest : global::ProtoBuf.IExtensible
  {
    public GetDayChargeAwardRequest() {}
    
    private int _index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TasteCardEnd")]
  public partial class TasteCardEnd : global::ProtoBuf.IExtensible
  {
    public TasteCardEnd() {}
    
    private int _cardType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"cardType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cardType
    {
      get { return _cardType; }
      set { _cardType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}