// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GameError.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GameError {

  /// <summary>Holder for reflection information generated from GameError.proto</summary>
  public static partial class GameErrorReflection {

    #region Descriptor
    /// <summary>File descriptor for GameError.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GameErrorReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9HYW1lRXJyb3IucHJvdG8SCmdhbWVfZXJyb3Iq7wEKCUVycm9yQ29kZRIO",
            "CgpFUlJPUl9OT05FEAASGAoURVJST1JfTk9fRlJFRV9TRVJWRVIQARIeChlF",
            "UlJPUl9MT0dJTl9BQ0NPVU5UX0VNUFRZEOgHEhoKFUVSUk9SX0xPR0lOX1BX",
            "RF9FTVBUWRDpBxIiCh1FUlJPUl9MT0dJTl9BQ0NPVU5UX05PVF9FWElTVBDq",
            "BxIUCg9FUlJPUl9MT0dJTl9QV0QQ6wcSHwoaRVJST1JfTE9HSU5fQ1JFQVRF",
            "X0FDQ09VTlQQ7AcSIQocRVJST1JfUkVHSVNURVJfQUNDT1VOVF9FWElTVBDy",
            "B2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::GameError.ErrorCode), }, null));
    }
    #endregion

  }
  #region Enums
  public enum ErrorCode {
    [pbr::OriginalName("ERROR_NONE")] ErrorNone = 0,
    /// <summary>
    /// 对不起，服务器正忙！
    /// </summary>
    [pbr::OriginalName("ERROR_NO_FREE_SERVER")] ErrorNoFreeServer = 1,
    /// <summary>
    /// 登录错误码
    /// </summary>
    [pbr::OriginalName("ERROR_LOGIN_ACCOUNT_EMPTY")] ErrorLoginAccountEmpty = 1000,
    /// <summary>
    /// 密码不为空
    /// </summary>
    [pbr::OriginalName("ERROR_LOGIN_PWD_EMPTY")] ErrorLoginPwdEmpty = 1001,
    /// <summary>
    /// 账号不存在
    /// </summary>
    [pbr::OriginalName("ERROR_LOGIN_ACCOUNT_NOT_EXIST")] ErrorLoginAccountNotExist = 1002,
    /// <summary>
    /// 密码错误
    /// </summary>
    [pbr::OriginalName("ERROR_LOGIN_PWD")] ErrorLoginPwd = 1003,
    /// <summary>
    /// 创建账号失败
    /// </summary>
    [pbr::OriginalName("ERROR_LOGIN_CREATE_ACCOUNT")] ErrorLoginCreateAccount = 1004,
    /// <summary>
    /// 账号存在
    /// </summary>
    [pbr::OriginalName("ERROR_REGISTER_ACCOUNT_EXIST")] ErrorRegisterAccountExist = 1010,
  }

  #endregion

}

#endregion Designer generated code
